name: CHCHRN
description: "Тимлид в Windy.app"
meta_description: "Andrey Chicherin, ios developer, teamlead, windy.app"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 1
baseurl: /
domain_name: "http://chchrn.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

telegram: chchrn
email: a@chchrn.com

# Details for the RSS feed generator
url: ""
author: "Andrey Chicherin"

# Disqus config
disqus-shortname: ""
